// eslint-disable-next-line no-unused-vars
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'bmw adapter settings': {
    en: 'Adapter settings for bmw',
    de: 'Adaptereinstellungen für bmw',
    ru: 'Настройки адаптера для bmw',
    pt: 'Configurações do adaptador para bmw',
    nl: 'Adapterinstellingen voor bmw',
    fr: "Paramètres d'adaptateur pour bmw",
    it: "Impostazioni dell'adattatore per bmw",
    es: 'Ajustes del adaptador para bmw',
    pl: 'Ustawienia adaptera dla bmw',
    'zh-cn': 'bmw2的适配器设置',
  },
  'App Email': {
    en: 'App Email',
    de: 'App-E-Mail',
    ru: 'Электронная почта приложения',
    pt: 'Email do aplicativo',
    nl: 'App-e-mail',
    fr: "Courriel de l'application",
    it: "E-mail dell'app",
    es: 'Correo electrónico de la aplicación',
    pl: 'E-mail aplikacji',
    'zh-cn': '应用电子邮件',
  },
  'App Password': {
    en: 'App Password',
    de: 'App-Passwort',
    ru: 'Пароль приложения',
    pt: 'Senha de app',
    nl: 'App-wachtwoord',
    fr: "Mot de passe de l'application",
    it: "Password dell'app",
    es: 'Contraseña de la aplicación',
    pl: 'Hasło do aplikacji',
    'zh-cn': '应用密码',
  },
  'Update interval (in minutes)': {
    en: 'Update interval (in minutes)',
    de: 'Aktualisierungsintervall (in Minuten)',
    ru: 'Интервал обновления (в минутах)',
    pt: 'Intervalo de atualização (em minutos)',
    nl: 'Update-interval (in minuten)',
    fr: 'Intervalle de mise à jour (en minutes)',
    it: 'Intervallo di aggiornamento (in minuti)',
    es: 'Intervalo de actualización (en minutos)',
    pl: 'Interwał aktualizacji (w minutach)',
    'zh-cn': '更新间隔（分钟）',
  },
  Brand: {
    en: 'Brand',
    de: 'Marke',
    ru: 'Марка',
    pt: 'Marca',
    nl: 'Brand',
    fr: 'Marque',
    it: 'Marca',
    es: 'Marca',
    pl: 'Brandy',
    'zh-cn': '陪审团',
  },
};
